site_name: Documentation-Test
site_description: python documentation test

theme: readthedocs
repo_name: wurDevTim/Documentation-Test
repo_url: https://github.com/wurDevTim/Documentation-Test
extra_css:
  - style.css

nav:
  - Home: index.md
  - Code: 
    - main: Code/main.md
    - models: Code/models.md
  - Changelog: CHANGELOG.md


markdown_extensions:
- pymdownx.snippets:
    check_paths: true

plugins: 
- mkdocstrings